# Generated by Django 4.0.1 on 2022-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prolductdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=50, null=True)),
                ('proprize', models.CharField(max_length=50, null=True)),
                ('prodesc', models.CharField(max_length=50, null=True)),
                ('proimage', models.ImageField(null=True, upload_to='proimage/')),
            ],
        ),
    ]
